import { FC } from "react";
import Provider from "./_trpc/provider";

type RootLayoutProps = {
  children: React.ReactNode;
};

export const metadata = {
  title: "Sample",
  description: "Generated by create next app",
};

const RootLayout: FC<RootLayoutProps> = (props) => {
  return (
    <html lang="ja">
      <body className="">
        <Provider>{props.children}</Provider>
      </body>
    </html>
  );
};

export default RootLayout;
